name: Publish Package

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: "Set up Python"
              uses: astral-sh/setup-uv@v6
              with:
                enable-cache: true

            - name: "Build"
              run: uv build

            - name: "Publish"
              run: uv publish